CREATE DATABASE IF NOT EXISTS ClinicManagementSystem CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ClinicManagementSystem;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS doctors;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS password_resets;
DROP TABLE IF EXISTS otp_verify;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;

-- 1. USERS: authentication and account information
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    role ENUM('patient','doctor','admin') NOT NULL DEFAULT 'patient',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 2. DOCTORS: doctor profile data; user_id links a doctor account to its profile
CREATE TABLE doctors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    CONSTRAINT fk_doctors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 3. PATIENTS: patient profile data
CREATE TABLE patients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    CONSTRAINT fk_patients_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 4. APPOINTMENTS: relationships only, no duplicated patient/doctor names
CREATE TABLE appointments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    status ENUM('pending','confirmed','completed','cancelled','rejected') NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 5. REPORTS: linked to an appointment; patient/doctor names are obtained by JOIN
CREATE TABLE reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    appointment_id INT NOT NULL,
    report_text TEXT NOT NULL,
    status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Support tables for OTP features
CREATE TABLE otp_verify (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(30) NOT NULL,
    otp VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE password_resets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    otp VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Seed users. Replace the password hashes with hashes generated by password_hash() if needed.
INSERT INTO users (name, username, email, password, phone, role) VALUES
('System Admin', 'admin', 'admin@clinic.local', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llCzF0fVhYb3oF6lJQxq', '01700000000', 'admin'),
('Dr. Alice', 'doctor1', 'doctor1@clinic.local', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llCzF0fVhYb3oF6lJQxq', '01700000001', 'doctor'),
('John Patient', 'patient1', 'patient1@clinic.local', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llCzF0fVhYb3oF6lJQxq', '01700000002', 'patient');

INSERT INTO doctors (user_id, name, specialization, phone)
SELECT id, name, 'General Medicine', phone FROM users WHERE username = 'doctor1';

INSERT INTO patients (user_id, name, phone, email)
SELECT id, name, phone, email FROM users WHERE username = 'patient1';

INSERT INTO appointments (patient_id, doctor_id, appointment_date, appointment_time, status)
SELECT p.id, d.id, '2026-08-20', '10:00:00', 'confirmed'
FROM patients p JOIN users pu ON pu.id = p.user_id
JOIN doctors d ON d.user_id IS NOT NULL
JOIN users du ON du.id = d.user_id
WHERE pu.username = 'patient1' AND du.username = 'doctor1';

-- CRUD examples for the Week 5 demonstration
-- CREATE: INSERT INTO doctors (name, specialization, phone) VALUES ('Dr. New', 'Cardiology', '01700000003');
-- READ: SELECT id, name, specialization FROM doctors ORDER BY name;
-- UPDATE: UPDATE appointments SET status = 'completed' WHERE id = 1;
-- DELETE: DELETE FROM appointments WHERE id = 1;
